version: '2'

networks:
    nuclear:

services:
    ca.org2.example.com:
        extends:
            file: docker-compose-base.yml
            service: ca
        container_name: ca.org2.example.com
        environment:
            - FABRIC_CA_SERVER_CA_NAME=ca-org2
            # TLS settings
            - FABRIC_CA_SERVER_TLS_CERFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
        volumes:
            - ./crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
        networks:
            - nuclear

    peer0.org2.example.com:
        extends:
            file: docker-compose-base.yml
            service: peer
        container_name: peer0.org2.example.com
        environment:
            - CORE_PEER_ID=peer0.org2.example.com
            - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
            - CORE_PEER_LOCALMSPID=Org2MSP
            # CouchDB settings
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
        depends_on:
            - couchdb2
        volumes:
            - /var/run/:/host/var/run/
            - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/:/etc/hyperledger/fabric/msp
            - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/:/etc/hyperledger/fabric/tls
            - ./crypto-config/peerOrganizations/org2.example.com/users/:/etc/hyperledger/users
        extra_hosts:
            - "orderer.example.com:IP_ORDERER"
            - "peer0.org1.example.com:IP_ORG1"
            - "peer0.org3.example.com:IP_ORG3"
            # UNCOMMENT FOR 5 ORGS NETWORK
            #- "peer0.org4.example.com:IP_ORG4"
            #- "peer0.org5.example.com:IP_ORG5"
        networks:
            - nuclear

    couchdb2:
        extends:
            file: docker-compose-base.yml
            service: couchdb
        container_name: couchdb2
        networks:
            - nuclear

    cli:
        container_name: cli
        image: hyperledger/fabric-tools
        tty: true
        environment:
            - GOPATH=/opt/gopath
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_LOGGING_LEVEL=DEBUG
            - CORE_PEER_ID=cli
            - CORE_PEER_ADDRESS=peer0.or2.example.com:7051
            - CORE_PEER_LOCALMSPID=Org2MSP
            - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp
            - CORE_CHAINCODE_KEEPALIVE=10
        extra_hosts:
            - "orderer.example.com:IP_ORDERER"
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - ./../chaincode/:/opt/gopath/src/github.com/chaincode
            - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
            - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        depends_on:
            - peer0.org2.example.com
        networks:
            - nuclear




    


